image: node

pages:
  stage: build
  script:
    - npm install
    - npm run build
    - npm run export
    - rm -rf public/*
    - mv out/* public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules/
      - build/cache/
  only:
    - main
